feature/wallet-model
jaimejazarenoiii/kwartracker-api pull request #1
Opened 2021-03-31 05:57 UTC by Jifflis

## Task
Add Wallet Model

## Ticket
https://trello.com/c/nl4MiP6M/5-wallet-model

2021-04-01 02:12 UTC, jaimejazarenoiii commented
Use PR tempalate

2021-04-01 02:18 UTC, jaimejazarenoiii requested changes

2021-04-01 02:18 UTC, jaimejazarenoiii commented on app/models/wallet.rb
> +	enum type: %i[type1 type2]
missing enum for currencies

2021-04-01 02:18 UTC, jaimejazarenoiii commented on db/schema.rb
> +  enable_extension "plpgsql"
again, rubocop will mark this as an offense, always make sure, overcommit is not bypassed 
<img width="1314" alt="Screen Shot 2021-04-01 at 10 17 16 AM" src="https://user-images.githubusercontent.com/32864278/113234253-814d1780-92d3-11eb-8f34-a16a4974d406.png">

2021-04-01 02:21 UTC, jaimejazarenoiii commented on db/migrate/20210331054326_create_wallets.rb
> +      t.string :title
missing extra properties for checking if this one is nullable

2021-04-13 07:01 UTC, jaimejazarenoiii commented on test/models/wallet_test.rb
> +  # test "the truth" do
Please add tests

2021-04-19 02:51 UTC, jaimejazarenoiii commented on app/models/wallet.rb
> +  validates :type, :currency, presence: true
I think type should be an enum also
normal and goal are the values

2021-05-07 10:19 UTC, rexendy approved these changes

2021-05-07 10:23 UTC, merged