Implement category list
jaimejazarenoiii/kwartracker-api pull request #20
Opened 2021-06-05 02:02 UTC by Jifflis

# 📲 What #
- Add category list api and test
 
# 🛠 How #
- Create resolver
- Create test
 
# ✅ Acceptance criteria #
- Category List 

# ⏰ TODO #
-none
 
# 🔗 References #
https://trello.com/c/nmSlMQ0G/18-list-categories-api

2021-06-22 02:17 UTC, jaimejazarenoiii requested changes

2021-06-22 02:17 UTC, jaimejazarenoiii commented on test/support/graphql/queries_helper.rb
> +            budgets{
spacing before `{`

2021-06-22 02:17 UTC, jaimejazarenoiii commented on test/support/graphql/queries_helper.rb
> +              amount,
comma is not necessary in queries

2021-06-28 07:36 UTC, jaimejazarenoiii requested changes

2021-06-28 07:36 UTC, jaimejazarenoiii commented on test/support/graphql/queries_helper.rb
> +            },
remove comma

2021-06-28 07:36 UTC, jaimejazarenoiii commented on test/graphql/queries/categories_query_test.rb
> +      assert_equal @json_response['categories'].count, 2
better to test the created categories(default after creation) so we know that the generation is done after creation of user

2021-07-27 06:13 UTC, rexendy approved these changes

2021-07-27 07:08 UTC, merged