feature/delete-category
jaimejazarenoiii/kwartracker-api pull request #23
Opened 2021-06-25 10:36 UTC by Jifflis

# 📲 What #
- Create delete category api
 
# 🛠 How #
- Create delete category mutation

# ✅ Acceptance criteria #
- Create Test
 
# ⏰ TODO #
None

# 🔗 References #
https://trello.com/c/MIVQ9xqN/32-delete-category

2021-06-28 07:55 UTC, jaimejazarenoiii requested changes

2021-06-28 07:55 UTC, jaimejazarenoiii commented on app/interactors/delete_category.rb
> +    @current_user = context[:current_user]
`@`

2021-06-28 07:55 UTC, jaimejazarenoiii commented on test/graphql/mutations/delete_category_test.rb
> +    test 'valid delete category' do
can we test the failures also? Like record not found

2021-06-28 07:55 UTC, jaimejazarenoiii commented on test/support/graphql/mutations_helper.rb
> +          $id: ID!,
no need for commas?

2021-06-28 07:55 UTC, jaimejazarenoiii commented on test/support/graphql/mutations_helper.rb
> +            id: $id,
same here

2021-07-28 05:51 UTC, rexendy approved these changes

2021-07-28 06:02 UTC, merged